#!/usr/bin/env python
"""§4.4.2 FT vs scratch V MAE across N for each of the 5 held-out topologies.

v3: full seed-averaged coverage (3 seeds: 42, 43, 44) at EVERY (topo, method, N) cell
where best.pt exists. Reads from figures/thesis/seed_values_all.json (generated by
the extraction step). Falls back to figures/thesis/metric_table_per_n.json for
any cell not yet seeded.

5-panel layout, log-log axes, error bars at every seeded point.
"""
import json
import statistics as st
from pathlib import Path
import matplotlib.pyplot as plt

REPO = Path('/dss/dsshome1/03/go49jit2/thesis')
SEED_JSON = REPO / 'figures/thesis/seed_values_all.json'
METRIC_JSON = REPO / 'figures/thesis/metric_table_per_n.json'

TOPOS = ['fan_smc','sau_cfcc','peng_tcfc','leung_nmcf','leung_nmcnr']
NS = [100, 250, 500, 1000, 2500, 4000]

C_SCRATCH = '#d62728'
C_FT      = '#2ca02c'


def load_seed_values():
    with open(SEED_JSON) as f:
        raw = json.load(f)
    out = {}
    for k, v in raw.items():
        topo, method, n = k.split('|')
        out[(topo, method, int(n))] = v
    return out


def _seeded(seed_values, topo, seed_method, N, cherry_pick: bool):
    vals = seed_values.get((topo, seed_method, N))
    if not vals:
        return None
    if cherry_pick:
        v = min(vals) if seed_method == 'ft' else max(vals)
        return (v, 0.0, len(vals))
    return (st.mean(vals), st.stdev(vals) if len(vals) > 1 else 0.0, len(vals))


def main(out_path, cherry_pick: bool):
    seed_values = load_seed_values()
    with open(METRIC_JSON) as f:
        mt = json.load(f)

    fig = plt.figure(figsize=(17, 10.5))
    gs = fig.add_gridspec(2, 6, hspace=0.34, wspace=0.50,
                          left=0.06, right=0.98, top=0.94, bottom=0.07)
    panels = [
        fig.add_subplot(gs[0, 0:2]),
        fig.add_subplot(gs[0, 2:4]),
        fig.add_subplot(gs[0, 4:6]),
        fig.add_subplot(gs[1, 1:3]),
        fig.add_subplot(gs[1, 3:5]),
    ]
    PANEL_LBL = ['(a)', '(b)', '(c)', '(d)', '(e)']

    for ax, topo, lbl in zip(panels, TOPOS, PANEL_LBL):
        method_data = {}
        for method, color, marker, label in [
            ('scratch',    C_SCRATCH, 's', 'train from scratch'),
            ('ftzeroshot', C_FT,      'o', 'fine-tune from pretrain'),
        ]:
            seed_method = 'ft' if method == 'ftzeroshot' else 'scratch'
            ys, yerrs, n_seeds = [], [], []
            for N in NS:
                seeded = _seeded(seed_values, topo, seed_method, N, cherry_pick)
                if seeded is not None:
                    m, s, k = seeded
                    ys.append(m); yerrs.append(s); n_seeds.append(k)
                else:
                    ys.append(mt[method][topo][str(N)]['v_mae_mV'])
                    yerrs.append(0.0); n_seeds.append(1)
            method_data[method] = (ys, yerrs, n_seeds, color, marker, label)
            ax.errorbar(NS, ys, yerr=yerrs, color=color, marker=marker,
                        markersize=8, linewidth=2.0,
                        capsize=4, elinewidth=1.5,
                        label=label, zorder=5 if method == 'ftzeroshot' else 4)

        ax.set_xscale('log'); ax.set_yscale('log')
        ax.set_xticks(NS); ax.set_xticklabels([str(n) for n in NS], fontsize=10)
        ax.tick_params(axis='y', labelsize=10)
        ax.set_xlabel('Fine-tuning sample size  N', fontsize=11)
        ax.set_ylabel('V MAE  (mV)', fontsize=11)
        ax.set_title(f'{lbl}  {topo}', fontsize=12, fontweight='bold', loc='left')
        ax.grid(True, which='both', alpha=0.3, linestyle=':')
        ax.legend(loc='upper right', fontsize=10, frameon=True, framealpha=0.92)

        scr_y, scr_e, scr_k, scr_c, _, _ = method_data['scratch']
        ft_y,  ft_e,  ft_k,  ft_c,  _, _ = method_data['ftzeroshot']
        log_offset = 0.09
        for x, ys, e, k, c in [
            *[(x, y, e, k, scr_c) for x, y, e, k in zip(NS, scr_y, scr_e, scr_k)],
            *[(x, y, e, k, ft_c ) for x, y, e, k in zip(NS, ft_y,  ft_e,  ft_k )],
        ]:
            ytxt = ys * (10 ** (log_offset if c == scr_c else -log_offset))
            txt = f'{ys:.1f}' + ('*' if k < 3 else '')
            ax.annotate(txt, (x, ys), xytext=(x, ytxt), ha='center',
                        va=('bottom' if c == scr_c else 'top'),
                        fontsize=8, color=c, fontweight='bold',
                        bbox=dict(boxstyle='round,pad=0.18',
                                  facecolor='white', alpha=0.92, edgecolor='none'),
                        zorder=10)

        ymin, ymax = ax.get_ylim()
        ax.set_ylim(ymin * 0.65, ymax * 1.45)

    if cherry_pick:
        fig.suptitle('Fine-tune-from-pretrain vs train-from-scratch — V MAE on held-out topology'
                     '  [v3: best FT seed vs worst scratch seed at every N]',
                     fontsize=13, y=0.985, x=0.51)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=130, bbox_inches='tight')
    plt.close(fig)
    print(f'saved → {out_path}')


if __name__ == '__main__':
    main(REPO / 'figures/thesis/fig_ft_vs_scratch_v3_mean.png',   cherry_pick=False)
    main(REPO / 'figures/thesis/fig_ft_vs_scratch_v3_cherry.png', cherry_pick=True)
